// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Config Web (Biarkan atau hapus tidak masalah karena kita fokus Android)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BQmuukqUTJT4rns11noZzlnL6zYz0qQ',
    appId: '1:332251256272:web:e0c991ede3c69dafc195d5',
    messagingSenderId: '332251256272',
    projectId: 'gps-tracker-45c2e',
    authDomain: 'gps-tracker-45c2e.firebaseapp.com',
    storageBucket: 'gps-tracker-45c2e.firebasestorage.app',
    measurementId: 'G-NTC6S4YQVN',
  );

  // Data diambil dari google-services.json project 'gpscollab'
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdw-X-shY74QS2GL5nOz8i0ppa20TBks', // Dari JSON baru
    appId: '1:1069303062412:android:19cbfba668e900705e40a9', // Dari JSON baru
    messagingSenderId: '1069303062412', // Dari JSON baru
    projectId: 'gpscollab', // Project kolaborasi
    storageBucket: 'gpscollab.firebasestorage.app',
    // Penting! Tambahkan URL database karena servernya di Asia
    databaseURL:
        'https://gpscollab-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  // Config iOS (Masih project lama, minta GoogleService-Info.plist jika mau update iOS)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4JU7uQOqa0hCs68zkZLbsGJD-By7PnI',
    appId: '1:332251256272:ios:fc92bb19406d3644c195d5',
    messagingSenderId: '332251256272',
    projectId: 'gps-tracker-45c2e',
    storageBucket: 'gps-tracker-45c2e.firebasestorage.app',
    iosBundleId: 'com.example.gpsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4JU7uQOqa0hCs68zkZLbsGJD-By7PnI',
    appId: '1:332251256272:ios:fc92bb19406d3644c195d5',
    messagingSenderId: '332251256272',
    projectId: 'gps-tracker-45c2e',
    storageBucket: 'gps-tracker-45c2e.firebasestorage.app',
    iosBundleId: 'com.example.gpsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2BQmuukqUTJT4rns11noZzlnL6zYz0qQ',
    appId: '1:332251256272:web:8ae57841a663b3ecc195d5',
    messagingSenderId: '332251256272',
    projectId: 'gps-tracker-45c2e',
    authDomain: 'gps-tracker-45c2e.firebaseapp.com',
    storageBucket: 'gps-tracker-45c2e.firebasestorage.app',
    measurementId: 'G-QGL5BYSH33',
  );
}
